Feat/product page
Norwen/fake-burrberry-frontend pull request #1
Opened 2017-08-03 07:42 UTC by Norwen

Расхождение на 1-2 пикселя начинается с блока "Shipping and returns"

2017-08-03 11:45 UTC, evgenyrodionov commented
отступы адовые в хтмл + нейминг тоже адовый, посмотри в сторону БЭМ

https://rawgit.com/Norwen/fake-burrberry-frontend/feat/product-page/index.html

2017-08-03 11:46 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28920418-6cb15b3e-785a-11e7-9636-98e294011871.png)
![image](https://user-images.githubusercontent.com/775692/28920426-7d3df5ca-785a-11e7-831b-377cff13a7e1.png)
![image](https://user-images.githubusercontent.com/775692/28920433-845424b0-785a-11e7-858b-c236c3613fae.png)

2017-08-04 07:33 UTC, imevro requested changes
- нейминг
- кнопки 
- иконки в разметке

2017-08-04 18:55 UTC, evgenyrodionov commented
Не коммить после запроса ревью — я из-за этого не знаю ты закончил или нет

2017-08-04 18:57 UTC, evgenyrodionov commented
Но навскидку норм, только нейминг додрочи

2017-08-06 01:34 UTC, Norwen commented
Проверила по чек-листу из телеграфа. Старалась избегать меджик намберс, которые могли возникнуть из-за неточностей в макетах цеплин. В мобильной версии отступы по 1рем, в планшетной 0.5 как в макете.

2017-08-06 20:49 UTC, imevro approved these changes

2017-08-06 20:50 UTC, merged