Feat/product page react
Norwen/fake-burrberry-frontend pull request #3
Opened 2017-08-11 16:44 UTC by Norwen

Без верстки под десктоп. Не смогла придумать, как поменять в русской локали название валюты.

2017-08-11 19:09 UTC, imevro requested changes
в целом норм, но поставь преттир + читай телеграф

2017-08-11 19:09 UTC, evgenyrodionov commented on src/App.css
> +@import url("https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i|Raleway:400,400i,500,500i,700,700i&amp;subset=cyrillic-ext");
через линкрел

2017-08-11 19:09 UTC, evgenyrodionov commented on src/App.css
> +* {
не-не, нахуй такое

2017-08-11 19:09 UTC, evgenyrodionov commented on src/App.js
> +        <div>
почему 4 пробела

2017-08-11 19:09 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
зачем классы

2017-08-11 19:09 UTC, evgenyrodionov commented on src/Product/Delivery/index.js
> +            <ParagraphHeader>Free Next Day Delivery</ParagraphHeader>
много префиксов

2017-08-11 19:09 UTC, evgenyrodionov commented on src/index.js
> +    <IntlProvider locale="ru">
нет, в `src/index.js` к реакту относится только `render(<App />)`, потому что не нужно плодить точки входа. Поэтому все провайдеры только в апп, не в индексе

2017-08-12 08:48 UTC, Norwen commented
Шрифты переподключила, отступы поправила, классы убрала лишние, провайдер вынесла в App. Начинаю десктоп.

2017-08-12 12:04 UTC, evgenyrodionov commented
Вижу коммиты после ревью — не понимаю, могу ли я проверять

2017-08-12 18:56 UTC, imevro requested changes
не понимаю нахуя я оставляю замечания если ты их игноришь

2017-08-12 18:56 UTC, evgenyrodionov commented on src/App.css
> +* {
и?

2017-08-12 18:56 UTC, evgenyrodionov commented on src/App.css
> +* {
смысл игнорить мои замечания?

2017-08-12 18:56 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
и?

2017-08-13 12:12 UTC, imevro requested changes
поставь преттир, реально

2017-08-13 12:12 UTC, evgenyrodionov commented on public/index.html
> +  <title>React App</title>
мусор

2017-08-13 12:12 UTC, evgenyrodionov commented on src/App.js
> +    return (
что с отступами, поставь преттир же

2017-08-13 12:12 UTC, evgenyrodionov commented on src/Product/Info/index.js
> +      <MetaInfo price="110000" article="39428531"/>
цену передавай числом

2017-08-13 12:12 UTC, evgenyrodionov commented on src/Product/Recommendations/RecommendationsMore/index.js
> +  const links = [
xml декларативнее джсона, поэтому обойдись без таких выкрутасов

2017-08-13 12:12 UTC, evgenyrodionov commented on src/Product/Recommendations/index.js
> +        <TitleCommon title="WE RECOMMEND"/>
проп тайтл → чилдрен

2017-08-13 12:12 UTC, evgenyrodionov commented on src/Product/Recommendations/index.js
> +      <RecommendationsMore/>
слишком много префиксов

2017-08-13 12:13 UTC, evgenyrodionov commented
Исправишь — напиши в телеграм

2017-08-13 12:15 UTC, evgenyrodionov commented
Не забудь сделать гит пулл, т.к. я добавил коммит мерджем

2017-08-13 17:45 UTC, imevro requested changes
смерджи через сквош после фикса

2017-08-13 17:45 UTC, evgenyrodionov commented on src/Product/TitleCommon.js
> +export default function(props) {
а зачем? делай сразу экспорт ск

2017-08-14 07:53 UTC, merged